version: '3.7'
services:
  materials:
    build: ./materials
    volumes:
      - ./materials/src:/app
    ports:
      - '8001:8001'

  defenses:
    build: ./defenses
    ports:
      - '8002:8002'
    environment:
      - REDIS_HOST=redis
      - MATERIALS_ENDPOINT=http://materials:8001/materials/
    depends_on:
      - redis
      - materials


  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always


  redis-browser:
    image: birkof/redis-browser
    command: --url redis://redis:6379 --bind 0.0.0.0
    ports:
      - 4567:4567
